version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    environment:
      - .env
    command: redis-server --requirepass $${REDIS_PASSWORD}--appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '$${REDIS_PASSWORD}', 'ping']
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
